apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: mentorplatform
  labels:
    app: mentorplatform-gateway
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  ASPNETCORE_HTTP_PORTS: "8080"
